### ISSUE TITLE
[Quality Improvment] Warnings in Luos code

### ISSUE THREAD

**Issue by JeromeGalan** [Luos-io/luos_engine#118]
On GitHub Action "BUILD" workflow, all Luos repository are correctly compiled, without any warning.
But on some OS (like Ubuntu), GCC basic parameters are generating too many warnings. 

Maybe those warnings are not relevant. But we should take a little time to think about that.

**Comment by nicolas-rabault** [comment]
We doesn't seems to have any warning anymore.
