### ISSUE TITLE
[NEW FEATURE] Move maximum of timestamp related code from HAL to engine

### ISSUE THREAD

**Issue by nicolas-rabault** [Luos-io/luos_engine#164]
Today we have in HAL a big part of the timestamp functions.

We have : 
 - ll_timestamp_t structure: In my point of view this should be on Luos, HAL should only allow getting back the current timestamp. Also the only value we need to have at a global level is start_offset. lower and higher timestamp are always calculated and we don't need to keep them.
 - LuosHAL_GetTimestamp: this one sounds good and should not take care about the start_offset if we consider this value as a Luos feature not related to hardware.
 - LuosHAL_StartTimestamp: If we consider the start_offset value as a Luos value this function should be on Luos side. Also instead of using a ms value why don't we use a ns offset?
 - LuosHAL_StopTimestamp: If we consider the start_offset value as a Luos value this function should be on Luos side. Other values don't need to be global so no need to reset them.

**Comment by JeromeGalan** [comment]
Done in  2.5.x
