### ISSUE TITLE
[NEW FEATURE] New LuosHAL_SetIrqState

### ISSUE THREAD

**Issue by Salem-Tho** [Luos-io/luos_engine#166]
**What feature would you like to be included in Luos?**
 It's will be nice in LuosHAL in the function LuosHAL_SetIrqState(uint8_t Enable) to just enable/disable LuosHAL interrupt and anot all the interrupt of the ship

**Comment by nicolas-rabault** [comment]
Luos_engine 3 call the IRQ function fo each PHY allowing the phy to only disable it's own IRQ.
