### ISSUE TITLE
[NEW FEATURE]  Header field Change

### ISSUE THREAD

**Issue by Salem-Tho** [Luos-io/luos_engine#169]
**What feature would you like to be included in Luos?**

Change positionning and name field of the header

Protocol change to Config
this fiels was on the 1st byte of the frame and now goes to the 3rd byte of the frame

Now
4--------12--------4--------12--------8------- 8
Proto---Target----Mode----Source----cmd---size

Then
12--------4--------4--------12--------8------- 8
Target----Mode---Config---Source---cmd---size

In the field config there is:
0 -> default value
1 -> time stamped msg

**Comment by ncros3** [comment]
protocol field has been renamed in #149
