### ISSUE TITLE
[BUG] Autoupdate crash after detection

### ISSUE THREAD

**Issue by JeromeGalan** [Luos-io/luos_engine#198]
**Describe the bug**
After many detections, a Node with autoupdate crashes. 
The context is described in the following pics :

<img width="794" alt="im1" src="https://user-images.githubusercontent.com/79972092/166721898-bb7a0d75-bfaf-485a-b42b-d71d58df9f4f.png">

<img width="881" alt="im2" src="https://user-images.githubusercontent.com/79972092/166721916-55e3a370-9114-4b68-8360-ad2903a8ba4e.png">

**Network configuration**
- Luos test platform :
1- Discovery F0 : Gate
2- Nucleo L4 : 15 Gpio
3- Nucleo G4 : Button  

**How to reproduce the bug**
Do many detections (random : sometimes about 20, sometimes about 200), 

**Additional context**
Most of the times the Gate sends an incomplete start detection and this event trigs the crash of Node 2. But sometimes, Node 2 is seems to be crashed without incomplete start detection.

**Comment by JeromeGalan** [comment]
Many asserts on L4 mem alloc. These problems seems to be linked with known bug : mem alloc reset sequence crashes a node when it occurs during Tx process.

**Comment by JeromeGalan** [comment]
Linked to #187

**Comment by JeromeGalan** [comment]
@BiliouriV : is it corrected ?

**Comment by BiliouriV** [comment]
Yes

**Comment by JeromeGalan** [comment]
Good ! Thank you :)

**Comment by JeromeGalan** [comment]
Done in 2.5.x
