### ISSUE TITLE
[BUG] LuosHAL_EraseMemory doesn't use its size parameter.

### ISSUE THREAD

**Issue by fleborne** [Luos-io/luos_engine#202]
**Describe the bug**

The declaration of `LuosHAL_EraseMemory` is 

```c
void LuosHAL_EraseMemory(uint32_t address, uint16_t size)
```

but the size parameter is not used in the function's implementation. The bootloader suffers from that while flashing a new firmware, as it erases all the flash instead of just what is needed to fit the new firmware.

**Network configuration**

No specific configuration.

**Comment by BiliouriV** [comment]
@JeromeGalan  Yes it is fixed. Now we use the size to delete the memory where it is possible (in case of boards with no sectors)

**Comment by JeromeGalan** [comment]
Already fixed
