### ISSUE TITLE
[NEW FEATURE] Deactivate the writing of aliases into Flash memory

### ISSUE THREAD

**Issue by BiliouriV** [Luos-io/luos_engine#214]
**What feature would you like to be included in Luos?**

An existing feature of Luos which is the subscription of aliases in flash memory should be deleted from Luos_engine, because it poses problems in the  writing of applications in flash and in the functionality of bootloader.

-Right now we reserve the last sector of the flash for the aliases that we may have defined, and that we may want to use in the future. However, it is not a functionality that is frequently needed by the users, and it is needed only in very specific projects (like in projects with numerous hot-pluged services of the same name, etc).

**Problems:**
->Up till now, as the aliases were saved in the last sector of flash, we didnt erase this sector. This causes a problem, if while using a bootloader we flash with an application binary that uses the last sector to be saved. For example a long binary application that takes maltiple sectors in order to be saved, or the example of NUCLEO-F410RB that we save directly the binary in the last flash sector. In other words, the flash of the application is not well-cleaned so the application upload fails.

->In the same condition with the previous problem, we can overwrite the aliases with an application, or we can overwrite some application bytes, with the aliases that are saved during the execution.

**Solution**
The best solution is to leave this feature in the users' decision. If users, developping a specific project, need to store the aliases of their services, they should write them into flash in the specific address that they want, into their user code.  So Luos will not handle the treatment of aliases, it will only change the alias in ram and it will not store it in flash.

The message of WRITE_ALIAS that may be sent by pyluos to the network in order to rename a service, should pass by Luos like before, so that Luos change the name of the service in the service structure, but it should also be transferred to the service. So if the user wants to stock this alias in flash, they can do it, otherwise the message will be dropped.

For the treatment of write alias message, as well as the writing of an alias in flash, it would be nice that we propose a tutorial, so that we could facilitate the process, and propose a solution for those that they need to use it.

**Comment by nicolas-rabault** [comment]
Luos_engine offers the possibility to rename the alias service through the Luos network. In this case, Luos store the new alias name in flash through luos_hal API and this stored alias will replace the alias name. Luos_engine keeps the default alias name to switch back in case of alias removal.
This functionality will remain the same but Luos won’t store the new alias name in flash through luos_hal API.
Users must develop this part if needed and use Luos API overwrite alias to replace the default alias create in service.
