### ISSUE TITLE
[BUG] messages not acked but still perfectly received

### ISSUE THREAD

**Issue by nicolas-rabault** [Luos-io/luos_engine#234]
**Which version the bug has been detected**
Luos engine 2.3.2

**Describe the bug**
I'm working on a critical application that need 100% message to be sent and not 99% or 101%. In this setup I see some really rare messages received and transmitted multiple time.
In this specific case I spotted a message NACKed but received on the user side : 
<img width="1257" alt="Screenshot 2022-05-20 at 14 55 45" src="https://user-images.githubusercontent.com/9554146/169533304-16c97916-60c0-4b13-ae1b-a1771a8fcfb6.png">

**Network configuration**
at least 2 nodes.

**How to reproduce the bug**
I have a data and I send the derivative form of this data. On the reception I compute the integral of this data after few time you can compare your data to see if there is any error.

**Comment by Salem-Tho** [comment]
fix in 2.8.0

**Comment by nicolas-rabault** [comment]
I seen this issue again in a different situation and figure it out! This is related to the looping of the message buffer.
