### ISSUE TITLE
[BUG] Bootloader cannot reflash after the flash of a gate

### ISSUE THREAD

**Issue by BiliouriV** [Luos-io/luos_engine#237]
** Which version the bug has been detected **
Luos engine 2.4.2

**Describe the bug**
Each time we flash a gate with the bootloader, so finally we have 2 gates and 2 pipes, and we want to reflash the node, the node is not responding, so we cannot reflash. However the network continues working, if we launch a detection we still have the 2 gates and 2 pipes

**Network configuration**
<img width="233" alt="Screenshot 2022-05-25 at 3 08 57 PM" src="https://user-images.githubusercontent.com/58600881/170269505-f7e6abfc-34cc-47e1-a93a-d262d89c4f1e.png">

and we flash with a gate binary.

**How to reproduce the bug**
Flash 1 time with a gate binary, and then try to reflash with any binary.

**Additional context**
Don't hesitate to add screenshots or to link an entry from the forum.
<img width="476" alt="Screenshot 2022-05-25 at 3 07 04 PM" src="https://user-images.githubusercontent.com/58600881/170269066-f45ada0f-5ef4-4340-84fb-8cb41dcf5c36.png">

**Comment by BiliouriV** [comment]
This was a Pyluos bug and it is resolved here: https://github.com/Luos-io/Pyluos/pull/144

**Comment by JeromeGalan** [comment]
Correctet in Pyluos release 2.2.2
