### ISSUE TITLE
[BUG] Suggestion - ID mode renaming

### ISSUE THREAD

**Issue by BiliouriV** [Luos-io/luos_engine#246]
** Which version the bug has been detected **
Luos engine X.Y.Z

**Describe the bug**
It is not  a bug, but it would be nice if the ID mode of Luos could be renamed to SERVICE or SERVICE_ID so that it would be easier to understand because an id can be node id topic id or service id.  That is to say we need to change every id instance in luos_engine robus and examples. This could be a part of the Luos clean of the next months

**Network configuration**
- Add the routing table or list the nodes and their services
- Power input configuration

**How to reproduce the bug**
Describe thoroughly the steps to reproduce the bug.

**Additional context**
Don't hesitate to add screenshots or to link an entry from the forum.

**Comment by JeromeGalan** [comment]
Fixe in 2.6.0
