### ISSUE TITLE
[BUG]  Code quality :  cleaning

### ISSUE THREAD

**Issue by JeromeGalan** [Luos-io/luos_engine#251]
**Describe the bug**
The code need a little "summer cleaning" to increase its quality :

- [x] Header functions: fix headers
- [x] inc folder in project rename include
- [x] Improve precompiled code identation
- [x] Definitions of BTN_Pin, LED_Pin in bootloader projects should not be defined - and maybe in other examples too
- [x] Clean bootloaders with old BOOTLOADER_MODE flags - update linkers, add WITH_BOOTLOADER flag
- [x] Node config comment had all define changable
- [x] Put INIT_TIME dans gate config
- [x] Change in files and all project ID and IDACK mode to SERVICE_ID  and SERVICE_IDACK mode cf #246
- [x] Rename potentiometre project in stm32l432kc
- [x] Remove uuid definition and call in code
- [x] Rename luos_stack_ratio to engine_msg_task
- [x] rmv .ino to cpp
- [x] See comments below for other actions on cleaning

**Comment by JeromeGalan** [comment]
Add : clean unit tests (timestamp, .etc..)

**Comment by BiliouriV** [comment]
@JeromeGalan I will just leave a comment here so that we do not forget to add the parameter MAX_RTB_ENTRY in the comments of node_config.h because it is a parameter that user could need to modify depending on their needs.

**Comment by BiliouriV** [comment]
NOT TO FORGET! In the boot app examples of G431 I forgot #ifdef BOOTLOADER_MODE in main.c and st files. It does not change anything, neither creates a bug. To remove.

**Comment by BiliouriV** [comment]
Also, we need to move the INIT_TIME from node_config.h to gate_config.h so that we dont have to define it in every gate project, and add only a comment to the node_config.h

**Comment by JeromeGalan** [comment]
Baudrate & luos_flush : should we remove these functions ?
