### ISSUE TITLE
[BUG] [Arduino] Missing header on Seeeduino XIAO M0

### ISSUE THREAD

**Issue by JeromeGalan** [Luos-io/luos_engine#257]
** Which version the bug has been detected **
Luos engine 2.4.1

**Describe the bug**
On Seeeduino XIAO M0, a header is missing : avr/pgmspace.h

This header can be found here :
framework-arduino-samd-seeed@https://github.com/Seeed-Studio/ArduinoCore-samd

**Comment by JeromeGalan** [comment]
This problem has been reported by @bhay_3DiTex

**Comment by Salem-Luos** [comment]
it was a pb from the lib seeeduino!
Works with version 1.8 but not with version 2.0 pb may come from that the lib use the usart peripherial for debugging
