### ISSUE TITLE
[BUG] Inspector searches for a GATEFORMAT

### ISSUE THREAD

**Issue by BiliouriV** [Luos-io/luos_engine#264]
** Which version the bug has been detected **
Luos engine 2.5.0

**Describe the bug**
We have a warning in the compilation of inspector_serial_com because the GATEFORMAT is undefined. That is to day the select_format_script.py in gate tool is being compiled, when we want to compile an inspector. We should not compile this file! I tested buid_src_filter = -./../....select_format_script.py but it doenst work exactly like this. To review...

**Network configuration**
- inspector_serial_com
- 
**How to reproduce the bug**
compile inspector

**Additional context**
Don't hesitate to add screenshots or to link an entry from the forum.

**Comment by JeromeGalan** [comment]
Fixed in luos_engine 2.6.2
