### ISSUE TITLE
[NEW FEATURE] Luos detect programming time

### ISSUE THREAD

**Issue by Salem-Tho** [Luos-io/luos_engine#265]
**What feature would you like to be included in Luos?**
Need to add a time when a detection must be lunch to avoid detection concurency

**Comment by Salem-Tho** [comment]
Document this part on how to change and what is the impact of the init time

**Comment by JeromeGalan** [comment]
The feature is developped.
We have to do a doc (troubleshooting) in 2.7.0

**Comment by JeromeGalan** [comment]
Fixed 2.6.0
