### ISSUE TITLE
[NEW FEATURE] Global routing table need or not to be send 

### ISSUE THREAD

**Issue by Salem-Tho** [Luos-io/luos_engine#270]
**What feature would you like to be included in Luos?**
In many case, a node don't need to receive and store the global routing, for exemple if there is only driver services in the node.

Now, we have to design ram message buffer to the size of global RTB in the product! it's necessary, just to accept message at detection time even if you only have one service in a node and after this phase all the space in the message buffer is useless.

Solution :

1. Add in node structure a bit field with information on the node.
one of them must indicate if the node need to receive the global RTB

struct __attribute__((__packed__))
{     // NODE mode entry
      struct __attribute__((__packed__))
      {
        uint16_t node_id : 12;  // Node id
        uint16_t certified : 4; // True if the node have a certificate
      };
      uint16_t port_table[(MAX_ALIAS_SIZE + 2 + 2 + sizeof(uint8_t) - 2) / 2]; // Node link table
      uint8_t Node_Info//Mask of flag information
};

2. In the mask field of Node_Info come from a define in node_config.h

3. At the of of a detection instead of sending the global routing table to all the node, the node who start the detction parse the global routing and the Node_Info bit field of each node to send or not the global routing table to the other node.

This way no need to filtering a spécial command in the reception just need to no send a global routing!

**Comment by JeromeGalan** [comment]
Fixed in luos_engine 2.6.0
