### ISSUE TITLE
[NEW FEATURE] Msg Alloc filtering

### ISSUE THREAD

**Issue by BiliouriV** [Luos-io/luos_engine#273]
**What feature would you like to be included in Luos?**
When we use polling to get messages, sometimes we want to pull messages of specific characteristics, as for example a specific tardet id, a topic of message, a type, a mode etc. For this reason an idea is to create a filtering method in msg alloc to filter and pull only the messages that we need. This is done only for topic messages right now but not with filtering method.

The inspiration of filtering method is the same with the routing table filtering.

However I am not sure if we need this feature, I have the impression that it can cause more problems than give solutions. 
Its just an idea to reconsider

**Comment by nicolas-rabault** [comment]
linked to #271
