### ISSUE TITLE
[BUG] Timing of the ackwnoledge with STM32F4

### ISSUE THREAD

**Issue by Salem-Tho** [Luos-io/luos_engine#388]
### Description of the bug
In the special case that you have an STM32F4 MCU in your network, you may have a problem with ack reception. 
Indeed in all other MCU, Luos use the busy flag to say if there is a byte receiving pending. for this family, there is no busy flag!
if a byte received is pending when a timeout happens luos wait for the end of the byte before performing an end of frame. On the MCU of the F4 family, the end of frame is directly performed and the ack will not be received

### How to reproduce the bug
It happen a lot when you have different MCU frequency in your network

### Possible solution
change Timeout to 30*bit time.
use detect_tx pin to catch a busy line (solution already coded but not always possible depending on user HW)

**Comment by BiliouriV** [comment]
This one poses problems to the bootloader version of 2.7.0 as we think that we flash the same node twice and we wait 2 responses from the same node while we get only 1...
