### ISSUE TITLE
[BUG] Bootloader failed when NO_RTB flag is definied in boot but not in APP

### ISSUE THREAD

**Issue by Salem-Tho** [Luos-io/luos_engine#389]
## Details
When you flash an application through the bootloader, if you have a bootloader binary WITHOUT the definition "NO_RTB" and an application WITH this define "NO_RTB" the first upload of the application works good! But when you try to reflash the application when you go back to the boot to reflash the application the bootloader hardfault

The application an the bootloader needs both to have the flag "NO_RTB" define  or both undefined!

this must be fix to be able to flash and configuration through the bootloader

**Comment by JeromeGalan** [comment]
This issue is closed : not reproducible.
It appeared on a bad configuration.
