### ISSUE TITLE
[BUG] PTP stucked to high level during booltloader data transfer

### ISSUE THREAD

**Issue by JeromeGalan** [Luos-io/luos_engine#391]
## Details
Please replace the italic test by your inputs and details in each of the following sections:

### Which version the bug has been detected on
*Luos engine 2.6.4*

### Description of the bug
The PTP is stucked to HIGH level after a 2nd flash with pyluos bootloader.

<img width="497" alt="ISSUE" src="https://user-images.githubusercontent.com/79972092/197002751-46f8c106-d09d-42de-b43f-19db2fd64e64.png">

### Context and environment
Gate L0 + Nucleo L432KC with a LED service

### How to reproduce the bug
The Nucleo was in bootloader mode. A Led service has been flashed with pyluos bootloader. We try to flash it a second time with the same service.

### Possible solution
Maybe we should do a "pyluos-bootloader reset" before each bootloader flash ? Or even call a reset automatically in bootloader machine state ?
To be verified : is it specified in the documentation ?

**Comment by JeromeGalan** [comment]
The salae trace is on my PC (Desktop\Timeline\Issue_391.sal)
Ask it on demands!

**Comment by nicolas-rabault** [comment]
Can't see this anymore.
