### ISSUE TITLE
[BUG] Patch long message ack

### ISSUE THREAD

**Issue by Salem-Tho** [Luos-io/luos_engine#408]
### Description of the bug
During detection, a large message was sometimes resent 2 times and create problem in the routing table. A patch was create to prevent this issue. Recently luos face the same problem in some configuration not only on large message. the bug come from an ack not receive by the sender. This problem will be solved by make the robus protocol more soft. Thias patch can be remove from the reception file

Thank you! Your issue will be reviewed by our admins.

**Comment by JeromeGalan** [comment]
Done in luos release 2.8.0
